apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: it19123882/ctse_it19123882:fe08ea3a99fa951e0993c28b05deca1e2d1f8a99
        ports:
        - containerPort: 3000