apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse3
spec:
  selector:
    matchLabels:
      app: ctse3
  replicas: 1
  template:
    metadata:
      labels:
        app: ctse3
    spec:
      containers:
      - name: ctse3
        image: it19123882/ctse_it19123882:5c3404f2b7c216a5379f3d838f33a516bc0dd930
        ports:
        - containerPort: 3000