apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctse3
  name: ctse3
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctse3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctse3
    spec:
      containers:
      - image: it19123882/ctse_it19123882:5c3404f2b7c216a5379f3d838f33a516bc0dd930
        imagePullPolicy: Always
        name: ctse-it19123882-qskcn
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30