apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse3
  name: ctse3
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ctse3
status:
  loadBalancer: {}