name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Build
      uses: okteto/actions/build@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          tag: ${{ secrets.DOCKER_USERNAME }}/ctse_it19123882:${{ github.sha }}
    - name: Get Kubeconfig
      uses: okteto/actions/namespace@v1
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: actions-aparna-jay
    - name: Deploy and Wait
      uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: actions-aparna-jay
          manifest: deploy.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/ctse_it19123882:${{ github.sha }}
          waitOn: deployment/ctse_it19123882
