on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: aparna-jay
   - name: "Trigger the pipeline"
     uses: okteto/pipeline@latest
     with:
       name: pr-${{ github.event.number }}
       timeout: 8m